### ISSUE TITLE
Build mod malformed code?

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#625]
### Subject 
Build mod malformed code?

### Environment
* Version of LPub3D - 2.4.5.8.3216 (latest DevOps)
Windows 10

### Steps to reproduce
![image](https://user-images.githubusercontent.com/32261647/204262141-5a9f380c-a2e6-4019-b427-94e982aeaff0.png)

Code

```
0 !LPUB BUILD_MOD BEGIN "Mod1"
1 71 150 24.9625 -123.785 0 0 -1 -0.247 0.969 0 0.969 0.247 0 3713.dat
1 2 100 24.9625 -123.785 0 0 1 0.969 0.247 0 -0.247 0.969 0 HashL4.dat
0 !LPUB BUILD_MOD END_MOD
1 71 70 26.035 -123.974 0 0 -1 -0.247 0.969 0 0.969 0.247 0 3713.dat
0 !LPUB BUILD_MOD END
0 STEP
0 !LPUB BUILD_MOD REMOVE "Mod1"
```

### Expected behaviour
This buildmod should be OK

### Actual behaviour
Error

### Workaround
None

### Solution suggestion
Is my code correct? This was generated by LPub3D and only the Mod name was modified by hand.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

Indeed, I’m treating this it ATM, see #621 and #622.

It looks like I did not merge the branch with the corrections for this behaviour into v2.4.5 master.

Anyway, as a heads up, you will also have an unexpected parse error when the last line in the sample code you provided is also in the last step of your submodel
(i.e the last line in the submodel).

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected - #621 and #622.

Cheers,

**Comment by jacovandermolen** [comment]
Version 2.4.5.24.3232_20221130 gives alle kind of errors with build mods:

![image](https://user-images.githubusercontent.com/32261647/204727152-0daed28c-fc02-4951-b274-2ac01a85965c.png)
![image](https://user-images.githubusercontent.com/32261647/204727211-cf41e512-71b0-49cb-a65f-b5b127424c59.png)
![image](https://user-images.githubusercontent.com/32261647/204727247-919af14a-5aca-474f-920f-20e32342621e.png)

After that crash. I will e-mail you my model file.

**Comment by trevorsandy** [comment]
> Version 2.4.5.24.3232_20221130 gives all kinds of errors with build mods:

Interesting, I'll take a look. 

Can you evaluate with _40252_mini_vw_beetle_?

[40252LPub243x.mpd.txt](https://github.com/trevorsandy/lpub3d/files/10120452/40252LPub243x.mpd.txt)

_40252_mini_vw_beetle_ is fairly thorough in presenting the build mod use cases I envisioned for helper parts and part substitution. For me, it processes and exports to PDF without any error messages. 

Let me know when you've sent your sample model file by email.

Cheers,

**Comment by jacovandermolen** [comment]
Hmm. Strange. The Beetle gives no problem.
Perhaps the code in my model is faulty then.
It did work in some previous versions though.
Maybe due to the use of Bufferexchange too?
I did that in step one because at one time a build mod in the first step
didn't work.

Op wo 30 nov. 2022 om 08:18 schreef Trevor SANDY ***@***.***>:

**Comment by jacovandermolen** [comment]
OK, I have a "header.ldr" file with many LPub settings, including
0 !LPUB BUILD_MOD_ENABLED GLOBAL TRUE
Moving this line to the main file, it seems to work!

I have to do some more testing with another model than my VW Beetle, that uses many more build mods.

One thing that seems weird is that upon going to page 2 I get an error for a submodel that is used way later in the model
![image](https://user-images.githubusercontent.com/32261647/204738584-147ab8b8-3101-4e63-a761-cf69fc0706de.png)

**Comment by trevorsandy** [comment]
Excellent, this is good, as it helps to point to way to a starting point.

> Moving this line to the main file, it seems to work!

You should not have to move your command. I'll take a look.

> One thing that seems weird is that upon going to page 2 I get an error for a submodel that is used way later in the model

This is because of the count page routine that must parse the entire model file to determine the number of pages to display. As you can imagine then, it is encountering an issue at mod 6 in submodel-24. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
> One thing that seems weird is that upon going to page 2 I get an error for a submodel that is used way later in the model

submodel-24.ldr Mod 6 and Mod 5 are in the same STEP. This configuration is not supported. The thinking is it is not efficient to have more than one build modification per step as a step is only rendered once.

One down, one to go...

Cheers,

**Comment by jacovandermolen** [comment]
> > One thing that seems weird is that upon going to page 2 I get an error for a submodel that is used way later in the model
> 
> `submodel-24.ldr Mod 6` and `submodel-24.ldr Mod 5` are in the same STEP. This configuration is not supported. The thinking is it is not efficient to have more than one build modification per step as a step is rendered once. Basically, `Mod 5` is read and `Mod 6` is ignored during registration. So when `Mod 6` is encountered in the count page routine, it is not found.
> 

Ah yes, my mistake I guess. I have to dig into this what I ment to achieve here. It is a somewhat difficult building technique to illustrate.

**Comment by trevorsandy** [comment]
> I have to dig into this what I ment to achieve here. It is a somewhat difficult building technique to illustrate.

Is it not reasonable to use a callout - if you prefer the keep the configuration within a single step ? 

With callouts, you can have as many build modifications as you like - as long as they are one per STEP.

TBH - I've designed the build mod infrastructure to accommodate more than one per STEP but along the way, I realized that less I also add a 'callout-like' behaviour to render individual build mods within a STEP, it would not make much sense to have more than one per STEP. Moreover, considering the build mod complexity, I don't want to add behaviour that is parallel to what is already available with callouts.

Cheers,

**Comment by jacovandermolen** [comment]
OK, I see. I will rethink the buildinginstructions then. Digging into my own work I realize it is too difficult.
I will find another way.

New problem: Build mods in first step do not seem to work?
In my example on page 9 is a callout with a build mod in step 1 (submodel 6)
This does not render and neither does the buildmod in the next step.

**Comment by trevorsandy** [comment]
> New problem: Build mods in first step do not seem to work?

I'll take a look.

Cheers,

**Comment by jacovandermolen** [comment]
> > New problem: Build mods in first step do not seem to work?
> 
> I'll take a look.

OK, DevOps version 2.4.5.42.3250 seems to have fixed this. Build mods work in first steps and in combination with NOSTEP.
However some other problems occur. See my comment [#632](https://github.com/trevorsandy/lpub3d/issues/632)

**Comment by trevorsandy** [comment]
Very well,

I'm a little bit confused between reviewing the emails and the tickets. If I well understand, since the last DevOps build, you now have two outstanding issues ?

1. #526 - Crash affects all the files you have attempted to clear formatting (or just a specific file ?) on all the builds tested.
2. #632 - Missing _Add Next Steps..._ menu action affects a specific file at a specific step-group configuration - more than 2 steps in the group.

Points of confusion for me.
- In the mails, there is an image from r42 showing a _Build Modification 'Mod 1' is not registered..._, is this behaviour resolved ?
- Additionally, there are two images showing _Could not find an index for TopOfStep fileName..._, is this behaviour also resolved ?

Cheers,

**Comment by jacovandermolen** [comment]
> I'm a little bit confused between reviewing the emails and the tickets. If I well understand, since the last DevOps build, you now have two outstanding issues ?
> 
> 1. [Using "Remove LPub formatting" causes a crash #526](https://github.com/trevorsandy/lpub3d/issues/526) - Crash affects all the files you have attempted to clear formatting (or just a specific file ?) on all the builds tested.
> 2. [Option to Add next steps... unavailable for submodel #632](https://github.com/trevorsandy/lpub3d/issues/632) - Missing _Add Next Steps..._ menu action affects a specific file at a specific step-group configuration - more than 2 steps in the group.

Yes.

> * In the mails, there is an image from r42 showing a _Build Modification 'Mod 1' is not registered..._, is this behaviour resolved ?
> * There is an image showing _BUILD_MOD REMOVE/APPLY action command must be placed before step parts_, is this behaviour resolved ?
> * Additionally, there are two images showing _Could not find an index for TopOfStep fileName..._, is this behaviour also resolved ?

These 3 are not resolved and occur in the latest DevOps version.
I thought I'd provide you with some example model files that have these problems, so you can test.

**Comment by trevorsandy** [comment]
The following outstanding items are all treated.

- [x] Remove LPub formatting causes crash #526
- [x] Option to add next steps unavailable #632
- [x] Build Mod message _Build Modification 'Mod 1' is not registered..._ #625
- [x] Build Mod message _BUILD_MOD REMOVE/APPLY action command must be placed before step parts..._ #642
- [x] Model file parse message _Could not find an index for TopOfStep fileName..._ #625

Cheers,

**Comment by jacovandermolen** [comment]
DevOps 2.4.5.62.3270 is working fine, so far!
I have done some intens testing and got everything to work the way I wanted.
Build Mods work, though I still get some errors and warnings, but in the end the result is what I should expect and want.
I will share my thoughts on that, the outcome of my tests and some successful BI of some models with you.
These all make heavy use of Build Mods (in in some cases good old Buffer exchange).
